### ISSUE TITLE
Web based translation using Hosted Weblate

### ISSUE THREAD

**Issue by ovari** [brainstormtrooper/facteur#70]
Can you please add your program to [Hosted Weblate](https://hosted.weblate.org/) to enable web-based translated to be added.

Thank you

**Comment by Vistaus** [comment]
+1

**Comment by brainstormtrooper** [comment]
https://hosted.weblate.org/projects/facteur/facteur-translations/

Is this what you're requesting?

**Comment by Vistaus** [comment]
Yes it is! Thanks for adding! 🙂

**Comment by ovari** [comment]
Translations for magyar (Hungarian) are 100% complete.

There are a few comments on Weblate.

Thank you

**Comment by brainstormtrooper** [comment]
Thanks for the translation and the comments
