### ISSUE TITLE
Add email address to `CC`, `BCC` and `Reply-To` fields

### ISSUE THREAD

**Issue by ovari** [brainstormtrooper/facteur#73]
Can email addresses please be added to [Cc (Carbon Copy)](https://en.wikipedia.org/wiki/Carbon_copy), [Bcc (Blind Carbon Copy, Blind Courtesy Copy)](https://en.wikipedia.org/wiki/Blind_carbon_copy) and [Reply to](https://en.wikipedia.org/wiki/Email#Reply-To) fields?

Thank you

**Comment by brainstormtrooper** [comment]
Done 0.19.1

**Comment by ovari** [comment]
Can the `Reply-To` field please also be added?

Below is a screenshot of [Thunderbird](https://www.thunderbird.net/)/[Betterbird](https://betterbird.eu/) showing the `Reply-To` field.

![image](https://github.com/brainstormtrooper/facteur/assets/17465872/b886c0e5-7c5d-4446-872b-3299a7b89ab5)

Thank you

**Comment by brainstormtrooper** [comment]
There's a Reply-To field also:
![image](https://github.com/brainstormtrooper/facteur/assets/393030/182da752-604a-429d-80fb-74952cf6dcf6)
